import { auth, db, signInAnonymously } from "./firebase.js";
import { ref,get,set,update,onValue,push,runTransaction,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
const $=id=>document.getElementById(id),views=["homeView","lobbyView","gameView","endView"];
let me=null,roomCode=null,room=null,unsub=null,chatUnsub=null,timerHandle=null,activeChat="living",audioCtx=null,musicOn=true,musicTimer=null,transitionLock=false;
const INVESTIGATION_SECONDS=10,DISCUSSION_SECONDS=60,VOTING_SECONDS=30,RESULT_SECONDS=8;
const ROLE_INFO={murderer:{label:"MURDERER",icon:"🔪",text:"Blend in. Choose a living target and coordinate secretly.",},detective:{label:"DETECTIVE",icon:"🕵️",text:"Investigate one living suspect each round. Your result is private."},investigator:{label:"INVESTIGATOR",icon:"🔎",text:"Search one living suspect for a private role check each round."},witness:{label:"WITNESS",icon:"👁️",text:"Your testimony can help narrow the timeline."},innocent:{label:"INNOCENT",icon:"👤",text:"Study the evidence, discuss carefully, and vote wisely."}};
const EVIDENCE=[
{type:"CASE CLUE",icon:"📌",title:"The West Corridor",text:"Someone moved through the west corridor without triggering the security alarm. The route is normally known only to residents and staff.",meta:"IMPLICATION · THE CULPRIT MAY HAVE KNOWN THE BUILDING"},
{type:"PHYSICAL EVIDENCE",icon:"🧪",title:"Broken Silver Watch",text:"A damaged silver watch was found beneath the library table. Its hands stopped at 22:17.",meta:"OBJECT · STOPPED TIME 22:17"},
{type:"WITNESS STATEMENT",icon:"👁️",title:"Statement #01",text:"I heard two sets of footsteps, then the west door slammed. I never saw their faces.",meta:"SOURCE · SECOND-FLOOR RESIDENT · RELIABILITY ★★★☆☆"},
{type:"FORENSIC REPORT",icon:"📄",title:"Preliminary Findings",text:"No forced entry was found. The estimated incident window is 22:10–22:25.",meta:"FORENSICS · ACCESS APPEARS VOLUNTARY"},
{type:"CCTV EVIDENCE",icon:"📹",title:"Camera 04 — West Hall",text:"A figure crosses the frame at 22:14. The image is too dark for a face, but the person appears to pause beside the service door.",meta:"SECURITY ARCHIVE · LOW CONFIDENCE"},
{type:"PHYSICAL EVIDENCE",icon:"🔑",title:"Service Key",text:"A brass service key was found on the floor. It opens the west corridor but was not listed as checked out.",meta:"OBJECT · UNREGISTERED ACCESS"}
];
const PHOTO={type:"CRIME SCENE PHOTOGRAPH",icon:"📸",title:"Library — 22:17",text:"Examine the scene. Three marked details are visible: the displaced chair, the stopped clock, and a dark reflection near the west window.",meta:"PHOTOGRAPH · ORIGINAL SCENE DOCUMENTATION"};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function showView(id){views.forEach(v=>$(v).classList.toggle("active",v===id))}function err(id,msg=""){const e=$(id);if(e)e.textContent=msg}function nameNorm(n){return n.trim().replace(/\s+/g," ").slice(0,20)}function code(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join("")}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function murderers(n){return n<=7?1:n<=14?2:n<=22?3:4}function specials(n){const a=[];if(n>=5)a.push("detective");if(n>=8)a.push("investigator");if(n>=10)a.push("witness");if(n>=18)a.push("witness");return a}
async function authIn(){if(!auth.currentUser)await signInAnonymously(auth);me=auth.currentUser;$("connection").textContent="● Online";$("connection").classList.add("online")}
async function createRoom(){const n=nameNorm($("nameInput").value);err("homeError");if(!n)return err("homeError","Enter your name first.");await authIn();let c=code(),exists=true;for(let i=0;i<5&&exists;i++){const s=await get(ref(db,`rooms/${c}`));exists=s.exists();if(exists)c=code()}if(exists)return err("homeError","Could not create a case. Try again.");roomCode=c;await set(ref(db,`rooms/${c}`),{hostUid:me.uid,status:"lobby",phase:"lobby",round:0,maxPlayers:30,createdAt:serverTimestamp(),players:{[me.uid]:{name:n,alive:true,joinedAt:serverTimestamp()}},public:{clueIndex:0,victimUid:"",winner:"",lastResult:null}});localStorage.setItem("mm_room",c);localStorage.setItem("mm_uid",me.uid);listenRoom(c)}
async function joinRoom(){const n=nameNorm($("nameInput").value),c=$("roomInput").value.trim().toUpperCase();err("homeError");if(!n)return err("homeError","Enter your name first.");if(!/^[A-Z0-9]{6}$/.test(c))return err("homeError","Enter a valid 6-character room code.");await authIn();const s=await get(ref(db,`rooms/${c}`));if(!s.exists())return err("homeError","Case not found.");const d=s.val(),ps=d.players||{};if(d.status!=="lobby")return err("homeError","This case has already started.");if(Object.keys(ps).length>=30)return err("homeError","This case is full.");const duplicate=Object.entries(ps).some(([uid,p])=>uid!==me.uid&&String(p.name||"").toLowerCase()===n.toLowerCase());if(duplicate)return err("homeError","That name is already in this case. Choose another name.");await set(ref(db,`rooms/${c}/players/${me.uid}`),{name:n,alive:true,joinedAt:serverTimestamp()});roomCode=c;localStorage.setItem("mm_room",c);localStorage.setItem("mm_uid",me.uid);listenRoom(c)}
function listenRoom(c){if(unsub)unsub();roomCode=c;unsub=onValue(ref(db,`rooms/${c}`),s=>{if(!s.exists()){showView("homeView");err("homeError","Case no longer exists.");return}room=s.val();render()});subscribeChat(activeChat)}
function render(){const ps=room.players||{},list=Object.entries(ps);$("roomCodeLabel").textContent=roomCode||"—";if(room.status==="lobby"){showView("lobbyView");$("playerCount").textContent=`${list.length}/30`;$('playerList').innerHTML=list.map(([uid,p])=>`<div class="player-row"><span class="avatar">${esc(String(p.name).slice(0,1).toUpperCase())}</span><span>${esc(p.name)}</span>${uid===room.hostUid?'<span class="host-label">HOST</span>':''}</div>`).join("");$("startBtn").disabled=me?.uid!==room.hostUid||list.length<4;$("startBtn").textContent=me?.uid!==room.hostUid?"Waiting for host…":list.length<4?`Need ${4-list.length} more player(s)`:"Start investigation";return}if(room.status==="playing"){showView("gameView");renderGame()}else if(room.status==="ended"){showView("endView");renderEnd()}}
function renderGame(){const phase=room.phase||"investigation",ps=room.players||{},mp=ps[me.uid],role=room.privateRoles?.[me.uid]?.role||"innocent",names={investigation:["INVESTIGATION","Examine the evidence."],discussion:["DISCUSSION","Compare stories. Trust carefully."],voting:["VOTING","Choose who you believe is responsible."],result:["CASE UPDATE","The vote has been recorded."]};$("phaseEyebrow").textContent=names[phase]?.[0]||phase.toUpperCase();$("phaseTitle").textContent=names[phase]?.[1]||"The case continues.";$("roundLabel").textContent=room.round||1;$("statusRound").textContent=String(room.round||1).padStart(2,"0");$("statusRoom").textContent=roomCode;const ri=ROLE_INFO[role];$("roleCard").innerHTML=`<div class="role-icon">${ri.icon}</div><div><div class="eyebrow">YOUR SECRET ROLE</div><h3>${ri.label}</h3><p>${ri.text}</p></div>`;renderEvidence(Number(room.public?.clueIndex||0));const alive=Object.entries(ps).filter(([,p])=>p.alive);$("aliveCount").textContent=`${alive.length} alive`;$('suspectList').innerHTML=alive.map(([uid,p])=>`<div class="suspect-row ${uid===me.uid?'me':''}"><span class="status-dot"></span>${esc(p.name)}</div>`).join("");renderAction(phase,role,mp);renderChatAccess(phase,mp,role);startTimer();}
function renderEvidence(i){const a=[EVIDENCE[i%EVIDENCE.length],EVIDENCE[(i+1)%EVIDENCE.length],i%2===0?PHOTO:EVIDENCE[(i+2)%EVIDENCE.length]];$("evidenceTags").innerHTML=a.map(x=>`<span class="pill">${x.icon} ${x.type}</span>`).join("");$("evidenceBoard").innerHTML=a.map((e,k)=>e===PHOTO?`<article class="evidence-item photo"><div class="evidence-type">${e.icon} ${e.type}</div><h4>${esc(e.title)}</h4><div class="crime-photo"><span class="photo-marker one">1</span><span class="photo-marker two">2</span><span class="photo-marker three">3</span></div><p>${esc(e.text)}</p><div class="evidence-meta">${esc(e.meta)}</div></article>`:`<article class="evidence-item" style="animation-delay:${k*60}ms"><div class="evidence-type">${e.icon} ${e.type}</div><h4>${esc(e.title)}</h4><p>${esc(e.text)}</p><div class="evidence-meta">${esc(e.meta)}</div></article>`).join("")}
function renderAction(phase,role,mp){const c=$("actionCard");if(!mp?.alive){c.innerHTML=`<div class="dead-box"><b>⚰️ YOU ARE ELIMINATED.</b><br>You can watch the case, but your living-room communication is locked.</div>`;return}const alive=Object.entries(room.players||{}).filter(([uid,p])=>p.alive&&uid!==me.uid);if(phase==="investigation"){if(role==="murderer")c.innerHTML=`<div class="card-title"><span>SECRET ACTION</span><span class="pill">🔪 PRIVATE</span></div><p>Choose one living target. The action resolves automatically.</p><div class="choice-grid">${alive.map(([uid,p])=>`<button class="choice-btn" data-action="target" data-uid="${uid}">${esc(p.name)}</button>`).join("")}</div>`;else if(role==="detective"||role==="investigator")c.innerHTML=`<div class="card-title"><span>PRIVATE INVESTIGATION</span><span class="pill">🔎 SECRET</span></div><p>Choose one living suspect. Your result is private.</p><div class="choice-grid">${alive.map(([uid,p])=>`<button class="choice-btn" data-action="inspect" data-uid="${uid}">${esc(p.name)}</button>`).join("")}</div><div id="privateResult" class="private-result"></div>`;else c.innerHTML=`<div class="card-title"><span>CASE REVIEW</span><span class="pill">READ</span></div><p>Study the evidence. Discussion begins automatically.</p>`;bindChoices()}else if(phase==="discussion")c.innerHTML=`<div class="card-title"><span>DISCUSSION</span><span class="pill">60 SECONDS</span></div><p>Compare evidence and challenge alibis. Voting opens automatically when the clock reaches zero.</p>`;else if(phase==="voting")c.innerHTML=`<div class="card-title"><span>CAST YOUR VOTE</span><span class="pill">PRIVATE</span></div><p>Your vote is hidden until the result is revealed.</p><div class="choice-grid">${alive.map(([uid,p])=>`<button class="choice-btn" data-action="vote" data-uid="${uid}">${esc(p.name)}</button>`).join("")}</div>`;bindChoices();else c.innerHTML=`<div class="result-box"><div class="eyebrow">ROUND RESULT</div><h3>${esc(room.public?.lastResult?.message||"The case is being updated.")}</h3></div>`}
function bindChoices(){document.querySelectorAll('.choice-btn').forEach(b=>b.addEventListener('click',async()=>{click();const a=b.dataset.action,u=b.dataset.uid;try{if(a==='target'){await set(ref(db,`rooms/${roomCode}/privateActions/${me.uid}`),{type:'target',targetUid:u});mark(b)}if(a==='inspect'){await set(ref(db,`rooms/${roomCode}/privateActions/${me.uid}`),{type:'inspect',targetUid:u});const box=$("privateResult"),t=room.players?.[u],r=room.privateRoles?.[u]?.role||'unknown';if(box)box.innerHTML=`<b>Private result:</b> ${esc(t?.name||'Player')} is ${r==='murderer'?'a MURDERER.':'not a murderer.'}`}if(a==='vote'){await set(ref(db,`rooms/${roomCode}/votes/${me.uid}`),{targetUid:u});mark(b);voteSound()}}catch(e){err('homeError',e.message)}}))}function mark(b){b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}
async function startGame(){if(me.uid!==room.hostUid)return;err('lobbyError');const entries=Object.entries(room.players||{});if(entries.length<4)return err('lobbyError','At least 4 players are required.');const roles=[...Array(murderers(entries.length)).fill('murderer'),...specials(entries.length)];while(roles.length<entries.length)roles.push('innocent');const shuffled=shuffle(roles),u={status:'playing',phase:'investigation',round:1,phaseEndsAt:Date.now()+INVESTIGATION_SECONDS*1000,'public/clueIndex':0,'public/victimUid':'','public/pendingVictimUid':'','public/lastResult':null,votes:null,privateActions:null};entries.forEach(([uid],i)=>u[`privateRoles/${uid}`]={role:shuffled[i]});await update(ref(db,`rooms/${roomCode}`),u);revealSound()}
async function advance(){if(!room||room.status!=='playing'||transitionLock)return;if(Date.now()<Number(room.phaseEndsAt||0))return;transitionLock=true;try{if(room.phase==='investigation')await toDiscussion();else if(room.phase==='discussion')await toVoting();else if(room.phase==='voting')await resolveVote();else if(room.phase==='result')await nextRound()}finally{setTimeout(()=>transitionLock=false,350)}}
async function toDiscussion(){await update(ref(db,`rooms/${roomCode}`),{phase:'discussion',phaseEndsAt:Date.now()+DISCUSSION_SECONDS*1000})}
async function toVoting(){const acts=room.privateActions||{},targets=Object.values(acts).filter(a=>a?.type==='target'&&room.players?.[a.targetUid]?.alive).map(a=>a.targetUid);let victim='';if(targets.length)victim=targets[Math.floor(Math.random()*targets.length)];await update(ref(db,`rooms/${roomCode}`),{phase:'voting',phaseEndsAt:Date.now()+VOTING_SECONDS*1000,votes:null,'public/pendingVictimUid':victim||''})}
async function resolveVote(){const votes=room.votes||{},counts={};Object.values(votes).forEach(v=>{if(v?.targetUid&&room.players?.[v.targetUid]?.alive)counts[v.targetUid]=(counts[v.targetUid]||0)+1});const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let accused='';if(top.length){const high=top[0][1],wins=top.filter(([,n])=>n===high).map(([uid])=>uid);if(wins.length===1)accused=wins[0]}const victim=room.public?.pendingVictimUid;const u={phase:'result',phaseEndsAt:Date.now()+RESULT_SECONDS*1000,'public/lastResult/message':accused?`${room.players[accused].name} was voted out.`:'The vote was tied or no vote was cast. Nobody was removed.','public/eliminatedUid':accused||'','public/eliminatedRole':accused?(room.privateRoles?.[accused]?.role||'unknown'):'','public/victimUid':victim||''};if(accused)u[`players/${accused}/alive`]=false;if(victim&&victim!==accused&&room.players?.[victim]?.alive){u[`players/${victim}/alive`]=false;u['public/lastResult/message']=(accused?`${room.players[accused].name} was voted out. `:'')+`${room.players[victim].name} was taken by the murderer.`}await update(ref(db,`rooms/${roomCode}`),u);if(accused){showElim(room.players[accused].name,room.privateRoles?.[accused]?.role);elimSound()}else if(victim){showElim(room.players[victim].name,room.privateRoles?.[victim]?.role);elimSound()}}
async function nextRound(){const alive=Object.entries(room.players||{}).filter(([,p])=>p.alive),am=alive.filter(([uid])=>room.privateRoles?.[uid]?.role==='murderer').length;if(am===0)return endGame('INNOCENTS WIN','All murderers have been identified.');if(am>=alive.length-am)return endGame('MURDERERS WIN','The murderers now control the investigation.');await update(ref(db,`rooms/${roomCode}`),{phase:'investigation',phaseEndsAt:Date.now()+INVESTIGATION_SECONDS*1000,round:Number(room.round||1)+1,votes:null,privateActions:null,'public/lastResult':null,'public/pendingVictimUid':'','public/victimUid':''})}
async function endGame(t,x){await update(ref(db,`rooms/${roomCode}`),{status:'ended',winner:t,winnerText:x});endSound()}
function renderEnd(){$('winnerTitle').textContent=room.winner||'Case closed.';$('winnerText').textContent=room.winnerText||'';const rs=room.privateRoles||{};$('finalRoles').innerHTML=Object.entries(room.players||{}).map(([uid,p])=>{const r=rs[uid]?.role||'unknown';return `<div class="final-role"><span>${esc(p.name)}</span><b>${esc(ROLE_INFO[r]?.label||r)}</b></div>`}).join('')}
function startTimer(){clearInterval(timerHandle);const tick=()=>{const ph=room?.phase||'',s=Math.max(0,Math.ceil((Number(room?.phaseEndsAt||0)-Date.now())/1000));$('timerLabel').textContent=ph==='discussion'?'DISCUSSION':ph==='voting'?'VOTING':ph==='result'?'CASE UPDATE':'INVESTIGATION';$('timer').textContent=`00:${String(s).padStart(2,'0')}`;if(s<=0){clearInterval(timerHandle);advance()} };tick();timerHandle=setInterval(tick,1000)}
function showElim(n,r){$('eliminationName').textContent=n;$('eliminationRole').textContent=`ROLE REVEALED · ${ROLE_INFO[r]?.icon||'?' } ${ROLE_INFO[r]?.label||r}`;$('eliminationOverlay').classList.remove('hidden');setTimeout(()=>$('eliminationOverlay').classList.add('hidden'),RESULT_SECONDS*1000-500)}
function canChat(ch,p,r){return ch==='living'?!!p?.alive:ch==='dead'?!p?.alive:r==='murderer'}function renderChatAccess(ph,p,r){document.querySelectorAll('.chat-tab').forEach(b=>{b.disabled=!canChat(b.dataset.chat,p,r);b.classList.toggle('hidden',!canChat(b.dataset.chat,p,r))});if(!canChat(activeChat,p,r)){activeChat=p?.alive?(r==='murderer'?'murderer':'living'):'dead';subscribeChat(activeChat)}const lock=ph==='voting'||ph==='result';$('chatLock').textContent=lock?'LOCKED':activeChat==='murderer'?'PRIVATE':'LIVE';$('chatNotice').textContent=lock?'Communications are locked while the vote is being recorded.':activeChat==='murderer'?'Encrypted murderer channel.':'Compare evidence and challenge alibis.';$('chatInput').disabled=lock||!canChat(activeChat,p,r);$('sendChatBtn').disabled=lock||!canChat(activeChat,p,r)}
function subscribeChat(ch){if(chatUnsub)chatUnsub();if(!roomCode)return;chatUnsub=onValue(ref(db,`rooms/${roomCode}/chats/${ch}`),s=>{const ms=Object.entries(s.val()||{}).sort((a,b)=>Number(a[1]?.createdAt||0)-Number(b[1]?.createdAt||0)).slice(-80);$('chatMessages').innerHTML=ms.map(([id,m])=>`<div class="message ${m.uid===me?.uid?'mine':''}"><div class="message-name">${esc(m.name||'Unknown')}</div><div class="message-text">${esc(m.text||'')}</div><div class="message-time">${new Date(Number(m.createdAt||Date.now())).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div>`).join('');$('chatMessages').scrollTop=$('chatMessages').scrollHeight})}
async function sendChat(){const i=$('chatInput'),t=i.value.trim(),p=room?.players?.[me.uid],r=room?.privateRoles?.[me.uid]?.role||'innocent';if(!t||!p||room.phase==='voting'||room.phase==='result'||!canChat(activeChat,p,r))return;await set(push(ref(db,`rooms/${roomCode}/chats/${activeChat}`)),{uid:me.uid,name:p.name,text:t,createdAt:Date.now()});i.value='';click()}
function setupChat(){document.querySelectorAll('.chat-tab').forEach(b=>b.addEventListener('click',()=>{if(b.disabled)return;click();activeChat=b.dataset.chat;document.querySelectorAll('.chat-tab').forEach(x=>x.classList.toggle('active',x.dataset.chat===activeChat));subscribeChat(activeChat)}));$('sendChatBtn').addEventListener('click',sendChat);$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()})}
function setup(){
$('createBtn').onclick=()=>{click();createRoom().catch(e=>err('homeError',e.message))};$('joinBtn').onclick=()=>{click();joinRoom().catch(e=>err('homeError',e.message))};$('startBtn').onclick=()=>{click();startGame().catch(e=>err('lobbyError',e.message))};$('backHomeBtn').onclick=()=>{click();if(unsub)unsub();if(chatUnsub)chatUnsub();room=null;roomCode=null;showView('homeView')};$('sendChatBtn').onclick=sendChat;$('musicBtn').onclick=()=>{musicOn=!musicOn;$('musicBtn').textContent=musicOn?'♫':'×';musicOn?music():stopMusic()};setupChat()}
function audio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}function tone(f,d=.08,type='sine',g=.025){if(!musicOn)return;const c=audio(),o=c.createOscillator(),x=c.createGain();o.type=type;o.frequency.value=f;x.gain.setValueAtTime(g,c.currentTime);x.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(x);x.connect(c.destination);o.start();o.stop(c.currentTime+d)}function click(){tone(170,.05,'triangle',.025)}function voteSound(){tone(240,.07,'triangle',.03);setTimeout(()=>tone(150,.1,'triangle',.02),70)}function revealSound(){tone(220,.12,'triangle',.025);setTimeout(()=>tone(330,.2,'triangle',.02),130)}function elimSound(){tone(75,.35,'sawtooth',.035);setTimeout(()=>tone(48,.5,'sine',.04),160)}function endSound(){tone(280,.15,'sine',.025);setTimeout(()=>tone(420,.3,'sine',.02),170)}function music(){stopMusic();let notes=[55,65.4,73.4,49,61.7,82.4],i=0;const loop=()=>{if(!musicOn)return;tone(notes[i++%notes.length],.7,'sine',.008);musicTimer=setTimeout(loop,900)};loop()}function stopMusic(){clearTimeout(musicTimer);musicTimer=null}
setup();window.addEventListener('load',async()=>{try{await authIn();music();const s=localStorage.getItem('mm_room');if(s){const snap=await get(ref(db,`rooms/${s}`));if(snap.exists()&&snap.val().status!=='ended'){roomCode=s;listenRoom(s)}}}catch(e){err('homeError','Firebase is not configured yet. Check firebase.js.')}});
